<h1 style="color:blue">Pivot basics</h1>

In [ ]:
# # prompt: open shared with me drive

# from google.colab import drive
# drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv("weather.csv")
df

       date      city  temperature  humidity
0  5/1/2024  new york           65        56
1  5/2/2024  new york           66        58
2  5/3/2024  new york           68        60
3  5/1/2024     dubai           75        80
4  5/2/2024     dubai           78        83
5  5/3/2024     dubai           82        85
6  5/1/2024   beijing           80        26
7  5/2/2024   beijing           77        30
8  5/3/2024   beijing           79        35

In [2]:
df.pivot(index='city',columns='date')

         temperature                   humidity
date        5/1/2024 5/2/2024 5/3/2024 5/1/2024 5/2/2024 5/3/2024
city
beijing           80       77       79       26       30       35
dubai             75       78       82       80       83       85
new york          65       66       68       56       58       60

In [3]:
df.pivot(index='city',columns='date',values="humidity")

date      5/1/2024  5/2/2024  5/3/2024
city
beijing         26        30        35
dubai           80        83        85
new york        56        58        60

In [4]:
df.pivot(index='date',columns='city')

         temperature                humidity
city         beijing dubai new york  beijing dubai new york
date
5/1/2024          80    75       65       26    80       56
5/2/2024          77    78       66       30    83       58
5/3/2024          79    82       68       35    85       60

In [5]:
df.pivot(index='humidity',columns='city')

              date                     temperature
city       beijing     dubai  new york     beijing dubai new york
humidity
26        5/1/2024       NaN       NaN        80.0   NaN      NaN
30        5/2/2024       NaN       NaN        77.0   NaN      NaN
35        5/3/2024       NaN       NaN        79.0   NaN      NaN
56             NaN       NaN  5/1/2024         NaN   NaN     65.0
58             NaN       NaN  5/2/2024         NaN   NaN     66.0
60             NaN       NaN  5/3/2024         NaN   NaN     68.0
80             NaN  5/1/2024       NaN         NaN  75.0      NaN
83             NaN  5/2/2024       NaN         NaN  78.0      NaN
85             NaN  5/3/2024       NaN         NaN  82.0      NaN

<h1 style="color:blue">Pivot Table</h1>

In [6]:
# df = pd.read_csv("/content/drive/MyDrive/weather2.csv")
# df

In [7]:
df.pivot_table(index="city",columns="date")

         humidity                   temperature
date     5/1/2024 5/2/2024 5/3/2024    5/1/2024 5/2/2024 5/3/2024
city
beijing      26.0     30.0     35.0        80.0     77.0     79.0
dubai        80.0     83.0     85.0        75.0     78.0     82.0
new york     56.0     58.0     60.0        65.0     66.0     68.0

<h2 style="color:brown">Margins</h2>

In [12]:
df.pivot_table(index="city",columns="date",margins=True,aggfunc=np.sum)

         humidity                        temperature
date     5/1/2024 5/2/2024 5/3/2024  All    5/1/2024 5/2/2024 5/3/2024  All
city
beijing        26       30       35   91          80       77       79  236
dubai          80       83       85  248          75       78       82  235
new york       56       58       60  174          65       66       68  199
All           162      171      180  513         220      221      229  670

<h2 style="color:brown">Grouper</h2>

In [13]:
# df = pd.read_csv("/content/drive/MyDrive/weather3.csv")
# # df

In [ ]:
df['date'] = pd.to_datetime(df['date'])

In [18]:
df.pivot_table(index=pd.Grouper(freq='ME',key='date'),columns='city')

TypeError: Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'Index'